GET http://localhost:4001/api/ping HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIxLTExLTI4VDEwOjMwOjMzLjM5NTQwOVoiLCJpc3MiOiJNYXR0aGlldSBMYWJzIFNSTCIsIm5hbWUiOiJKYW5leiBOb3ZhayIsInN1YiI6MX0.YcJimrYIMhd4xdgQv7ldknt2-Wqg8X7NxboLJxrXqkE